name: Feature Request
description: Suggest an idea
labels: [feature]
title: '[Feature]:'
body:
  - type: textarea
    id: description
    attributes:
      description: 원하시는 기능을 설명해주세요.
      label: Description
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      placeholder: I think this is probably...
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: etc.
    validations:
      required: false
